services:
  redis-server:
    image: redis:6.2
    restart: 'always'
    container_name: redis-server
    ports:
      - '6379:6379'
    #  volumes:
    #    - ./redis.conf:/etc/redis/redis.conf
    #    - ./data:/data
    #  command: redis-server /etc/redis/redis.conf
    privileged: true

  redis-cli:
    image: redis:6.2
    restart: 'always'
    container_name: redis-cli
    command: bash -c 'redis-cli -h redis-server -p 6379 ping; while true; do sleep 20220101; done'
    privileged: true
  # nest-backend:
  #   container_name: nest-app
  #   image: nest-api
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   ports:
  #     - 5000:5000
  #   environment:
  #     - DB_HOST=localhost
  #     - DB_PORT=3307
  #     - DB_USER=root
  #     - DB_PASSWORD=00000000
  #     - DB_NAME=product_be
  #   networks:
  #     - backend_network
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: unless-stopped
networks:
  backend_network: 'localhost'
